// Generated by CoffeeScript 1.4.0

jQuery(function() {
  $.each($("[data-time]"), function(index, ele) {
    return $(ele).html(prettyDate(new Date($(this).data("time"))));
  });
  $.each($("a[id]"), function(index, ele) {
    return $(ele).click(function(e) {
      e.stopImmediatePropagation();
      return _gaq.push(["_trackEvent", "Clicks", "clicked", e.target.id]);
    });
  });
  return $.each($("a:not([id])"), function(index, ele) {
    return $(ele).click(function(e) {
      e.stopImmediatePropagation();
      console.log(e.currentTarget.innerText);
      return _gaq.push(["_trackEvent", "Visits", "clicked on " + e.currentTarget.innerText, e.currentTarget.href]);
    });
  });
});
