// Generated by CoffeeScript 1.4.0

jQuery(function() {
  var max_scroll;
  $.each($("[data-time]"), function(index, ele) {
    return $(ele).html(prettyDate(new Date($(this).data("time"))));
  });
  max_scroll = $(window).height() - document.body.clientHeight;
  $(window).scroll(function() {
    var offset, scroll_pos, sidebar_pos;
    scroll_pos = window.pageYOffset;
    sidebar_pos = $("#sidebar").offset().top;
    if (scroll_pos < max_scroll) {
      offset = scroll_pos > sidebar_pos && $(window).width() > 640 ? scroll_pos - sidebar_pos + 10 : 5;
      return $("#sidebar").css("padding-top", offset + "px");
    }
  });
  $.each($("a[id]"), function(index, ele) {
    return $(ele).click(function(e) {
      e.stopImmediatePropagation();
      return _gaq.push(["_trackEvent", "Clicks", "clicked", e.target.id]);
    });
  });
  return $.each($("a:not([id])"), function(index, ele) {
    return $(ele).click(function(e) {
      e.stopImmediatePropagation();
      console.log(e.currentTarget.innerText);
      return _gaq.push(["_trackEvent", "Visits", "clicked on " + e.currentTarget.innerText, e.currentTarget.href]);
    });
  });
});
